/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADIV
 */
public class MainMustahiq extends javax.swing.JFrame {

    /**
     * Creates new form MainMustahiq
     */
    
    private Connection conn = null;
    private Statement stmt = null;
    private ResultSet rs = null;
    
    
    public MainMustahiq() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Mustahiq = new javax.swing.JPanel();
        jLabel_IDMustahiq = new javax.swing.JLabel();
        jTextField_idMustahiq = new javax.swing.JTextField();
        jLabel_NamaMustahiq = new javax.swing.JLabel();
        jTextField_namaMustahiq = new javax.swing.JTextField();
        jComboBox_golMustahiq = new javax.swing.JComboBox<>();
        jLabel_golMustahiq = new javax.swing.JLabel();
        jLabel_alamatMustahiq = new javax.swing.JLabel();
        jTextField_alamatMustahiq = new javax.swing.JTextField();
        jScrollPane_mustahiq = new javax.swing.JScrollPane();
        jTableMustahiq = new javax.swing.JTable();
        jButton_tambahMustahiq = new javax.swing.JButton();
        jButton_updateMustahiq = new javax.swing.JButton();
        jButton_deleteMustahiq = new javax.swing.JButton();
        jButton_kembaliMustahiq = new javax.swing.JButton();
        jLabel_judulMustahiq = new javax.swing.JLabel();
        jButton_ResetMustahiq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Mustahiq.setBackground(new java.awt.Color(44, 62, 80));
        jPanel_Mustahiq.setPreferredSize(new java.awt.Dimension(829, 464));

        jLabel_IDMustahiq.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_IDMustahiq.setText("ID Mustahiq");

        jLabel_NamaMustahiq.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NamaMustahiq.setText("Nama");

        jTextField_namaMustahiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_namaMustahiqActionPerformed(evt);
            }
        });

        jComboBox_golMustahiq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fakir", "Miskin", "Gharim", "Riqab", "Mualaf", "Fisabilillah", "Ibnu Sabil", "Amil Zakat" }));

        jLabel_golMustahiq.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_golMustahiq.setText("Golongan");

        jLabel_alamatMustahiq.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_alamatMustahiq.setText("Alamat");

        jTableMustahiq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_mustahiq.setViewportView(jTableMustahiq);

        jButton_tambahMustahiq.setBackground(new java.awt.Color(51, 255, 51));
        jButton_tambahMustahiq.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_tambahMustahiq.setText("Tambah");
        jButton_tambahMustahiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambahMustahiqActionPerformed(evt);
            }
        });

        jButton_updateMustahiq.setBackground(new java.awt.Color(0, 255, 204));
        jButton_updateMustahiq.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_updateMustahiq.setText("Update");
        jButton_updateMustahiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateMustahiqActionPerformed(evt);
            }
        });

        jButton_deleteMustahiq.setBackground(new java.awt.Color(255, 0, 51));
        jButton_deleteMustahiq.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_deleteMustahiq.setText("Delete");

        jButton_kembaliMustahiq.setBackground(new java.awt.Color(204, 255, 255));
        jButton_kembaliMustahiq.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_kembaliMustahiq.setText("Kembali");

        jLabel_judulMustahiq.setBackground(new java.awt.Color(187, 187, 187));
        jLabel_judulMustahiq.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel_judulMustahiq.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_judulMustahiq.setText("Data Mustahiq");

        jButton_ResetMustahiq.setBackground(new java.awt.Color(255, 204, 204));
        jButton_ResetMustahiq.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_ResetMustahiq.setText("Reset");

        javax.swing.GroupLayout jPanel_MustahiqLayout = new javax.swing.GroupLayout(jPanel_Mustahiq);
        jPanel_Mustahiq.setLayout(jPanel_MustahiqLayout);
        jPanel_MustahiqLayout.setHorizontalGroup(
            jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                        .addComponent(jLabel_judulMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                        .addComponent(jScrollPane_mustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                                .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_NamaMustahiq)
                                    .addComponent(jLabel_golMustahiq))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MustahiqLayout.createSequentialGroup()
                                .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton_kembaliMustahiq))
                                    .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                                                .addComponent(jLabel_IDMustahiq)
                                                .addGap(64, 64, 64))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_MustahiqLayout.createSequentialGroup()
                                                .addComponent(jLabel_alamatMustahiq)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_alamatMustahiq)
                                            .addComponent(jTextField_namaMustahiq)
                                            .addComponent(jTextField_idMustahiq)
                                            .addComponent(jComboBox_golMustahiq, 0, 188, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_MustahiqLayout.createSequentialGroup()
                                        .addComponent(jButton_tambahMustahiq)
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton_ResetMustahiq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_updateMustahiq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(52, 52, 52)
                                        .addComponent(jButton_deleteMustahiq)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(742, 742, 742))))))
        );
        jPanel_MustahiqLayout.setVerticalGroup(
            jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel_judulMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane_mustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_MustahiqLayout.createSequentialGroup()
                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_IDMustahiq)
                            .addComponent(jTextField_idMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NamaMustahiq)
                            .addComponent(jTextField_namaMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_golMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_golMustahiq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_alamatMustahiq)
                            .addComponent(jTextField_alamatMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel_MustahiqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_tambahMustahiq)
                            .addComponent(jButton_updateMustahiq)
                            .addComponent(jButton_deleteMustahiq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ResetMustahiq)
                        .addGap(23, 23, 23)
                        .addComponent(jButton_kembaliMustahiq)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Mustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Mustahiq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_tambahMustahiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambahMustahiqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_tambahMustahiqActionPerformed

    private void jButton_updateMustahiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateMustahiqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_updateMustahiqActionPerformed

    private void jTextField_namaMustahiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_namaMustahiqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_namaMustahiqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMustahiq().setVisible(true);
            }
        });
    }

    public JButton getjButton_deleteMustahiq() {
        return jButton_deleteMustahiq;
    }

    public JButton getjButton_kembaliMustahiq() {
        return jButton_kembaliMustahiq;
    }

    public JButton getjButton_tambahMustahiq() {
        return jButton_tambahMustahiq;
    }

    public JButton getjButton_updateMustahiq() {
        return jButton_updateMustahiq;
    }

    public String getjComboBox_golMustahiq() {
        return jComboBox_golMustahiq.getSelectedItem().toString();
    }

    public JTable getjTableMustahiq() {
        return jTableMustahiq;
    }
    public int getSelectedMustahiq(){
        return jTableMustahiq.getSelectedRow();
    }

    public String getjTextField_alamatMustahiq() {
        return jTextField_alamatMustahiq.getText();
    }

    public String getjTextField_idMustahiq() {
        return jTextField_idMustahiq.getText();
    }

    public String getjTextField_namaMustahiq() {
        return jTextField_namaMustahiq.getText();
    }

    public void setjComboBox_golMustahiq(String x) {
        jComboBox_golMustahiq.setSelectedItem(x);
    }

    public void setjTableMustahiq(DefaultTableModel x) {
        jTableMustahiq.setModel(x);
    }

    public void setjTextField_alamatMustahiq(String x) {
        jTextField_alamatMustahiq.setText(x);
    }

    public void setjTextField_idMustahiq(String x) {
        jTextField_idMustahiq.setText(x);
    }

    public void setjTextField_namaMustahiq(String x) {
        jTextField_namaMustahiq.setText(x);
    }
    
    public void addActionListener(ActionListener x){
        jButton_deleteMustahiq.addActionListener(x);
        jButton_kembaliMustahiq.addActionListener(x);
        jButton_tambahMustahiq.addActionListener(x);
        jButton_updateMustahiq.addActionListener(x);
        jButton_ResetMustahiq.addActionListener(x);
    }
    
    public void addMouseAdapter(MouseAdapter x){
        jTableMustahiq.addMouseListener(x);
    }
    public void showMessage(String message,String title,int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }

    public JButton getjButton_ResetMustahiq() {
        return jButton_ResetMustahiq;
    }
    public void Reset(){
        jTextField_idMustahiq.setText("");
        jTextField_namaMustahiq.setText("");
        jTextField_alamatMustahiq.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ResetMustahiq;
    private javax.swing.JButton jButton_deleteMustahiq;
    private javax.swing.JButton jButton_kembaliMustahiq;
    private javax.swing.JButton jButton_tambahMustahiq;
    private javax.swing.JButton jButton_updateMustahiq;
    private javax.swing.JComboBox<String> jComboBox_golMustahiq;
    private javax.swing.JLabel jLabel_IDMustahiq;
    private javax.swing.JLabel jLabel_NamaMustahiq;
    private javax.swing.JLabel jLabel_alamatMustahiq;
    private javax.swing.JLabel jLabel_golMustahiq;
    private javax.swing.JLabel jLabel_judulMustahiq;
    private javax.swing.JPanel jPanel_Mustahiq;
    private javax.swing.JScrollPane jScrollPane_mustahiq;
    private javax.swing.JTable jTableMustahiq;
    private javax.swing.JTextField jTextField_alamatMustahiq;
    private javax.swing.JTextField jTextField_idMustahiq;
    private javax.swing.JTextField jTextField_namaMustahiq;
    // End of variables declaration//GEN-END:variables
}


