/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Mustahiq;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADIV
 */
public class MainZakat extends javax.swing.JFrame {

    /**
     * Creates new form MainZakat
     */
     private Connection conn = null;
     private Statement stmt = null;
     private ResultSet rs = null;
     
     
     
    public MainZakat() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Zakat = new javax.swing.JPanel();
        jScrollPane_zakat = new javax.swing.JScrollPane();
        jTableZakat = new javax.swing.JTable();
        jLabel_idZakat = new javax.swing.JLabel();
        jLabel_idMustahiq = new javax.swing.JLabel();
        jTextField_idZakat = new javax.swing.JTextField();
        jComboBox_idMustahiq = new javax.swing.JComboBox<>();
        jLabel_namaZakat = new javax.swing.JLabel();
        jTextField_namaZakat = new javax.swing.JTextField();
        jButton_tambahZakat = new javax.swing.JButton();
        jButton_updateZakat = new javax.swing.JButton();
        jButton_deleteZakat = new javax.swing.JButton();
        jButton_kembaliZakat = new javax.swing.JButton();
        jLabel_judulZakat = new javax.swing.JLabel();
        jButton_ResetZakat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Zakat.setBackground(new java.awt.Color(44, 62, 80));

        jTableZakat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane_zakat.setViewportView(jTableZakat);

        jLabel_idZakat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_idZakat.setText("ID Zakat");

        jLabel_idMustahiq.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_idMustahiq.setText("ID Mustahiq");

        jLabel_namaZakat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_namaZakat.setText("Nama Zakat");

        jButton_tambahZakat.setBackground(new java.awt.Color(51, 255, 51));
        jButton_tambahZakat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_tambahZakat.setText("Tambah");
        jButton_tambahZakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambahZakatActionPerformed(evt);
            }
        });

        jButton_updateZakat.setBackground(new java.awt.Color(0, 255, 204));
        jButton_updateZakat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_updateZakat.setText("Update");

        jButton_deleteZakat.setBackground(new java.awt.Color(255, 0, 0));
        jButton_deleteZakat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_deleteZakat.setText("Delete");

        jButton_kembaliZakat.setBackground(new java.awt.Color(204, 255, 255));
        jButton_kembaliZakat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_kembaliZakat.setText("Kembali");

        jLabel_judulZakat.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jLabel_judulZakat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_judulZakat.setText("Data Zakat");

        jButton_ResetZakat.setBackground(new java.awt.Color(204, 204, 255));
        jButton_ResetZakat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_ResetZakat.setText("Reset");

        javax.swing.GroupLayout jPanel_ZakatLayout = new javax.swing.GroupLayout(jPanel_Zakat);
        jPanel_Zakat.setLayout(jPanel_ZakatLayout);
        jPanel_ZakatLayout.setHorizontalGroup(
            jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ZakatLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_judulZakat, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(jScrollPane_zakat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_ZakatLayout.createSequentialGroup()
                            .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_idZakat)
                                .addComponent(jLabel_idMustahiq)
                                .addComponent(jLabel_namaZakat))
                            .addGap(21, 21, 21)
                            .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_idZakat)
                                .addComponent(jComboBox_idMustahiq, 0, 249, Short.MAX_VALUE)
                                .addComponent(jTextField_namaZakat)))
                        .addGroup(jPanel_ZakatLayout.createSequentialGroup()
                            .addComponent(jButton_tambahZakat)
                            .addGap(61, 61, 61)
                            .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_ResetZakat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_updateZakat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                            .addComponent(jButton_deleteZakat)))
                    .addGroup(jPanel_ZakatLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton_kembaliZakat)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel_ZakatLayout.setVerticalGroup(
            jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ZakatLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel_judulZakat, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_ZakatLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane_zakat, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel_ZakatLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_idZakat)
                            .addComponent(jTextField_idZakat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_idMustahiq)
                            .addComponent(jComboBox_idMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_namaZakat)
                            .addComponent(jTextField_namaZakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel_ZakatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_tambahZakat)
                            .addComponent(jButton_updateZakat)
                            .addComponent(jButton_deleteZakat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ResetZakat)
                        .addGap(42, 42, 42)
                        .addComponent(jButton_kembaliZakat)
                        .addGap(51, 51, 51))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Zakat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Zakat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_tambahZakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambahZakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_tambahZakatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainZakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainZakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainZakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainZakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainZakat().setVisible(true);
            }
        });
    }

    public JButton getjButton_deleteZakat() {
        return jButton_deleteZakat;
    }

    public JButton getjButton_kembaliZakat() {
        return jButton_kembaliZakat;
    }

    public JButton getjButton_tambahZakat() {
        return jButton_tambahZakat;
    }

    public JButton getjButton_updateZakat() {
        return jButton_updateZakat;
    }

    public String getjComboBox_idMustahiq() {
        return jComboBox_idMustahiq.getSelectedItem().toString();
    }
    public int getSelectedZakat(){
        return jTableZakat.getSelectedRow();
    }

    public String getjTextField_idZakat() {
        return jTextField_idZakat.getText();
    }

    public String getjTextField_namaZakat() {
        return jTextField_namaZakat.getText();
    }

    public void setjComboBox_idMustahiq(String x) {
        jComboBox_idMustahiq.setSelectedItem(x);
    }

    public void setjTextField_idZakat(String x) {
        jTextField_idZakat.setText(x);
    }

    public void setjTextField_namaZakat(String x) {
        jTextField_namaZakat.setText(x);
    }

    public JTable getjTableZakat() {
        return jTableZakat;
    }

    public void setjTableZakat(DefaultTableModel x) {
        jTableZakat.setModel(x);
    }
    public void addActionListener(ActionListener ae){
        jButton_ResetZakat.addActionListener(ae);
        jButton_deleteZakat.addActionListener(ae);
        jButton_kembaliZakat.addActionListener(ae);
        jButton_tambahZakat.addActionListener(ae);
        jButton_updateZakat.addActionListener(ae);
    }

    public JButton getjButton_ResetZakat() {
        return jButton_ResetZakat;
    }

   
    public void addMouseAdapter(MouseAdapter x){
        jTableZakat.addMouseListener(x);
    }
    public void showMessage(String message,String title,int type){
        JOptionPane.showMessageDialog(null, message, title, type);
        
    }
    
    public void Reset(){
        jTextField_idZakat.setText("");
        jTextField_namaZakat.setText("");
    }
    
    public void isiMustahiq(){
       try{
           String query = "SELECT id from mustahiq";
           conn = DriverManager.getConnection("jdbc:mysql://localhost/zakat", "root", "");
           stmt = conn.createStatement();
           rs = stmt.executeQuery(query);
           while(rs.next()){
               jComboBox_idMustahiq.addItem(rs.getString("id"));
           }
           conn.close();
           stmt.close();
           
       }catch(SQLException e){
           System.out.println(e);
       }
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ResetZakat;
    private javax.swing.JButton jButton_deleteZakat;
    private javax.swing.JButton jButton_kembaliZakat;
    private javax.swing.JButton jButton_tambahZakat;
    private javax.swing.JButton jButton_updateZakat;
    private javax.swing.JComboBox<String> jComboBox_idMustahiq;
    private javax.swing.JLabel jLabel_idMustahiq;
    private javax.swing.JLabel jLabel_idZakat;
    private javax.swing.JLabel jLabel_judulZakat;
    private javax.swing.JLabel jLabel_namaZakat;
    private javax.swing.JPanel jPanel_Zakat;
    private javax.swing.JScrollPane jScrollPane_zakat;
    private javax.swing.JTable jTableZakat;
    private javax.swing.JTextField jTextField_idZakat;
    private javax.swing.JTextField jTextField_namaZakat;
    // End of variables declaration//GEN-END:variables

    
}
